import React, { useState, useEffect } from 'react';
import { Download, Eye, Search, X } from 'lucide-react';
import type { InvestigationResponse } from '../types/investigation';
import { getStoredMissions, downloadReport } from '../api/investigations';
import { formatDateTime, formatConfidencePercent } from '../utils/formatters';

const getConfidenceInfo = (confidence?: any) => {
  if (!confidence) return { score: undefined, label: 'N/A', model: 'Consensus engine' };
  const conf = Array.isArray(confidence) ? (confidence[0] ?? null) : confidence;
  if (!conf) return { score: undefined, label: 'N/A', model: 'Consensus engine' };
  const score = conf.score !== undefined ? conf.score : conf.confidence;
  const label = conf.label || 'N/A';
  const model = conf.associated_model || conf.model?.name || 'Consensus engine';
  return { score, label, model };
};

export const ReportsPage: React.FC = () => {
  const [reports, setReports] = useState<InvestigationResponse[]>([]);
  const [search, setSearch] = useState<string>('');
  const [previewReport, setPreviewReport] = useState<InvestigationResponse | null>(null);

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = () => {
    const missions = getStoredMissions();
    setReports(missions);
  };

  const handleDownload = async (id: string) => {
    try {
      await downloadReport(id);
    } catch (err: any) {
      alert(`Report download failed: ${err.message}`);
    }
  };

  const filteredReports = reports.filter(
    (r) =>
      r.investigation_id.toLowerCase().includes(search.toLowerCase()) ||
      r.query.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-3 border-b border-neutral-800">
        <div>
          <h1 className="text-sm font-semibold text-neutral-100">
            Investigation reports
          </h1>
          <p className="text-xs text-neutral-400 mt-0.5">
            Technical audit reports generated by the agentic pipeline
          </p>
        </div>

        <button
          onClick={loadReports}
          className="px-3 py-1.5 rounded bg-neutral-900 hover:bg-neutral-850 text-xs text-neutral-300 border border-neutral-800 transition-colors"
        >
          Refresh
        </button>
      </div>

      {/* Search Filter */}
      <div className="relative max-w-md">
        <Search className="w-3.5 h-3.5 text-neutral-500 absolute left-3 top-2.5" />
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search reports by ID or query..."
          className="w-full bg-neutral-900 border border-neutral-800 rounded pl-9 pr-3 py-1.5 text-xs text-neutral-200 font-sans focus:outline-none focus:border-neutral-700"
        />
      </div>

      {/* Reports Table */}
      <div className="bg-neutral-900 border border-neutral-800 rounded-lg overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-sans">
            <thead className="bg-neutral-950/80 text-[11px] text-neutral-400 border-b border-neutral-800">
              <tr>
                <th className="px-4 py-2.5 font-medium">Report file</th>
                <th className="px-4 py-2.5 font-medium">Directive</th>
                <th className="px-4 py-2.5 font-medium">Timestamp</th>
                <th className="px-4 py-2.5 font-medium">Confidence</th>
                <th className="px-4 py-2.5 font-medium">Status</th>
                <th className="px-4 py-2.5 text-right font-medium">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-800">
              {filteredReports.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-4 py-8 text-center text-neutral-500 text-xs">
                    No investigation reports found.
                  </td>
                </tr>
              ) : (
                filteredReports.map((r) => {
                  const isCompleted = r.status === 'completed';
                  return (
                    <tr key={r.investigation_id} className="hover:bg-neutral-850/50 transition-colors">
                      <td className="px-4 py-3 font-mono text-xs text-neutral-300 whitespace-nowrap">
                        SatQuery_Report_{r.investigation_id}.md
                      </td>

                      <td className="px-4 py-3 max-w-md truncate text-neutral-300" title={r.query}>
                        {r.query}
                      </td>

                      <td className="px-4 py-3 font-mono text-neutral-500 whitespace-nowrap text-[11px]">
                        {formatDateTime(r.created_at)}
                      </td>

                      <td className="px-4 py-3 font-mono whitespace-nowrap">
                        {isCompleted ? (
                          <span className="text-status-success font-medium">
                            {formatConfidencePercent(getConfidenceInfo(r.execution?.confidence).score)}
                          </span>
                        ) : (
                          <span className="text-neutral-500">N/A</span>
                        )}
                      </td>

                      <td className="px-4 py-3 whitespace-nowrap">
                        <span
                          className={`text-[11px] font-medium ${
                            isCompleted ? 'text-status-success' : 'text-status-error'
                          }`}
                        >
                          {isCompleted ? 'Completed' : 'Failed'}
                        </span>
                      </td>

                      <td className="px-4 py-3 text-right whitespace-nowrap">
                        <div className="flex items-center justify-end gap-2">
                          <button
                            type="button"
                            onClick={() => setPreviewReport(r)}
                            className="flex items-center gap-1 px-2 py-1 rounded bg-neutral-950 hover:bg-neutral-850 text-neutral-300 border border-neutral-800 text-xs transition-colors"
                          >
                            <Eye className="w-3 h-3 text-neutral-400" />
                            <span>Preview</span>
                          </button>

                          <button
                            type="button"
                            onClick={() => handleDownload(r.investigation_id)}
                            className="flex items-center gap-1 px-2 py-1 rounded bg-neutral-850 hover:bg-neutral-800 text-neutral-200 border border-neutral-700 text-xs transition-colors"
                          >
                            <Download className="w-3 h-3 text-neutral-400" />
                            <span>Download</span>
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Preview Modal */}
      {previewReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-neutral-950/70 backdrop-blur-xs">
          <div className="bg-neutral-900 border border-neutral-800 rounded-lg max-w-2xl w-full max-h-[85vh] flex flex-col shadow-xl overflow-hidden">
            <div className="flex items-center justify-between px-6 py-4 border-b border-neutral-800 bg-neutral-950">
              <span className="text-xs font-mono text-neutral-300 font-medium">
                Report preview: {previewReport.investigation_id}
              </span>
              <button
                onClick={() => setPreviewReport(null)}
                className="p-1 rounded text-neutral-400 hover:text-neutral-200"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-6 overflow-y-auto text-xs text-neutral-300 space-y-4 font-mono">
              <div className="border border-neutral-800 p-3 rounded bg-neutral-950 space-y-1">
                <div className="text-neutral-200 font-bold">
                  SATQUERY AI — INVESTIGATION REPORT
                </div>
                <div>ID: {previewReport.investigation_id}</div>
                <div>Directive: "{previewReport.query}"</div>
                <div>Status: {previewReport.status}</div>
                <div>Date: {previewReport.created_at || 'N/A'}</div>
              </div>

              <div className="border border-neutral-800 p-3 rounded bg-neutral-950 space-y-1 font-sans">
                <div className="text-xs font-semibold text-neutral-200">1. Finding summary</div>
                <p className="text-neutral-300 leading-relaxed">
                  {previewReport.finding?.summary || 'No summary available.'}
                </p>
                {previewReport.finding?.answer && (
                  <p className="text-neutral-400 pt-1 text-xs">
                    {previewReport.finding.answer}
                  </p>
                )}
              </div>

              <div className="border border-neutral-800 p-3 rounded bg-neutral-950 space-y-1 text-xs">
                <div className="font-semibold text-neutral-200 font-sans">2. Confidence assessment</div>
                <div>
                  Score: {formatConfidencePercent(getConfidenceInfo(previewReport.execution?.confidence).score)} ({getConfidenceInfo(previewReport.execution?.confidence).label})
                </div>
                <div>
                  Model: {getConfidenceInfo(previewReport.execution?.confidence).model}
                </div>
                <div>
                  Evidence count: {previewReport.execution?.evidence?.length || 0} items
                </div>
              </div>
            </div>

            <div className="px-6 py-3 border-t border-neutral-800 bg-neutral-950 flex justify-end gap-2">
              <button
                onClick={() => handleDownload(previewReport.investigation_id)}
                className="flex items-center gap-1.5 px-3 py-1.5 bg-neutral-800 hover:bg-neutral-700 text-neutral-100 text-xs font-medium rounded transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download (.md)</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
